spring:
  profiles:
    active: prod


#    //default, prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/trendMart
    password: 2020
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: uwamahorosonia1@gmail.com
    password: lrsi qjwm hxkz gzfr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  flyway:
    baseline-on-migrate: true
    repair-on-migrate: true


