spring:
  profiles:
    active: default
  #    //default, prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/TrendMart_EcommercePlatform
    password: Alice@123
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    username: uwamahorosonia1@gmail.com
    password: lrsi qjwm hxkz gzfr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    port: 8080
  server:
    port=8081:

flutterwave:
  secret-key:
  base-url: