spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TrendMart_EcommercePlatform
    username: postgres
    password: Alice@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    baseline-on-migrate: true

  application:
    name: TrendMart_EcommercePlatform
