spring:
  config:
    activate:
      on-profile:default
        #default,prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/TrendMart_EcommercePlatform
    username: postgres
    password: Alice@123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true

logging:
  level:
    com.zaxxer.hikari: DEBUG
#   org.springframework.jdbc.datasource: DEBUG
