spring:
  profiles:
    active: default
#    //default, prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/trendmart-ecommerce-platform
    password: Ineza2005
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: uwamahorosonia1@gmail.com
    password: lrsi qjwm hxkz gzfr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


    spring:
      flyway:
        repair-on-migrate: true




