spring:
  profiles:
    active: prod
#    //default
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/trendmart-ecommerce-platform
    password: Ineza2005
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  flyway:
    baseline-on-migrate: true