spring:
  profiles:
    active: default
  #    //default, prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/TrendMart_EcommercePlatform
    password: Alice@123
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  flyway:
    baseline-on-migrate: true