ALTER TABLE product_image_urls
DROP
CONSTRAINT fk_product_imageurls_on_product;

CREATE TABLE wishlist_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT,
    product_id BIGINT,
    added_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_wishlistitem PRIMARY KEY (id)
);

ALTER TABLE wishlist_item
    ADD CONSTRAINT FK_WISHLISTITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE wishlist_item
    ADD CONSTRAINT FK_WISHLISTITEM_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

DROP TABLE product_image_urls CASCADE;

DROP SEQUENCE reviews_seq CASCADE;