CREATE TABLE category
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    price       DECIMAL,
    image_url   VARCHAR(255),
    sku_code    VARCHAR(255),
    brand       VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    category_id BIGINT,
    stock_id    BIGINT,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE product_urls
(
    product_id BIGINT NOT NULL,
    urls       VARCHAR(255)
);

CREATE TABLE stock
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_stock PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    username      VARCHAR(255),
    email         VARCHAR(255),
    phone_number  VARCHAR(255),
    password      VARCHAR(255),
    date_of_birth TIMESTAMP WITHOUT TIME ZONE,
    role          VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE product
    ADD CONSTRAINT uc_product_stock UNIQUE (stock_id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_STOCK FOREIGN KEY (stock_id) REFERENCES stock (id);

ALTER TABLE product_urls
    ADD CONSTRAINT fk_product_urls_on_product FOREIGN KEY (product_id) REFERENCES product (id);