CREATE SEQUENCE IF NOT EXISTS reviews_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE address
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street      VARCHAR(255),
    city        VARCHAR(255),
    state       VARCHAR(255),
    country     VARCHAR(255),
    postal_code VARCHAR(255),
    is_default  BOOLEAN,
    user_id     BIGINT,
    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE discount
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title               VARCHAR(255),
    description         VARCHAR(255),
    discount_percentage DOUBLE PRECISION,
    active              BOOLEAN,
    start_date          date                                    NOT NULL,
    end_date            date                                    NOT NULL,
    CONSTRAINT pk_discount PRIMARY KEY (id)
);

CREATE TABLE reviews
(
    id         BIGINT  NOT NULL,
    rating     INTEGER NOT NULL,
    comment    VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id    BIGINT,
    product_id BIGINT,
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);

ALTER TABLE product
    ADD discount_id BIGINT;

ALTER TABLE address
    ADD CONSTRAINT uc_address_user UNIQUE (user_id);

ALTER TABLE product
    ADD CONSTRAINT uc_product_discount UNIQUE (discount_id);

ALTER TABLE address
    ADD CONSTRAINT FK_ADDRESS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_DISCOUNT FOREIGN KEY (discount_id) REFERENCES discount (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);