CREATE TABLE payment
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tx_ref         VARCHAR(255),
    transaction_id VARCHAR(255),
    status         VARCHAR(255),
    amount         INTEGER                                 NOT NULL,
    currency       VARCHAR(255),
    email          VARCHAR(255),
    first_name     VARCHAR(255),
    last_name      VARCHAR(255),
    payment_time   TIMESTAMP WITHOUT TIME ZONE,
    order_id       BIGINT,
    CONSTRAINT pk_payment PRIMARY KEY (id)
);

ALTER TABLE payment
    ADD CONSTRAINT uc_payment_order UNIQUE (order_id);

ALTER TABLE payment
    ADD CONSTRAINT FK_PAYMENT_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

DROP TABLE payments CASCADE;