CREATE TABLE IF NOT EXISTS cart
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_cart PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cartitems
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cart_id    BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    quantity   INTEGER,
    CONSTRAINT pk_cartitems PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS order_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT                                  NOT NULL,
    quantity   INTEGER,
    price      DECIMAL,
    order_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_orderitem PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS orders
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    total_amount   DECIMAL,
    status         VARCHAR(255),
    payment_method VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    address_id     BIGINT,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

-- Add constraints only if they don't exist (using lowercase names)
DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints
                       WHERE constraint_name = 'uc_cart_user' AND table_name = 'cart') THEN
            ALTER TABLE cart ADD CONSTRAINT uc_cart_user UNIQUE (user_id);
        END IF;
    END $$;

DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints
                       WHERE constraint_name = 'fk_cartitems_on_cart' AND table_name = 'cartitems') THEN
            ALTER TABLE cartitems ADD CONSTRAINT fk_cartitems_on_cart FOREIGN KEY (cart_id) REFERENCES cart (id);
        END IF;
    END $$;

DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints
                       WHERE constraint_name = 'fk_cartitems_on_product' AND table_name = 'cartitems') THEN
            ALTER TABLE cartitems ADD CONSTRAINT fk_cartitems_on_product FOREIGN KEY (product_id) REFERENCES product (id);
        END IF;
    END $$;

DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints
                       WHERE constraint_name = 'fk_cart_on_user' AND table_name = 'cart') THEN
            ALTER TABLE cart ADD CONSTRAINT fk_cart_on_user FOREIGN KEY (user_id) REFERENCES users (id);
        END IF;
    END $$;

DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints
                       WHERE constraint_name = 'fk_orderitem_on_order' AND table_name = 'order_item') THEN
            ALTER TABLE order_item ADD CONSTRAINT fk_orderitem_on_order FOREIGN KEY (order_id) REFERENCES orders (id);
        END IF;
    END $$;

DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints
                       WHERE constraint_name = 'fk_orderitem_on_product' AND table_name = 'order_item') THEN
            ALTER TABLE order_item ADD CONSTRAINT fk_orderitem_on_product FOREIGN KEY (product_id) REFERENCES product (id);
        END IF;
    END $$;

DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints
                       WHERE constraint_name = 'fk_orders_on_address' AND table_name = 'orders') THEN
            ALTER TABLE orders ADD CONSTRAINT fk_orders_on_address FOREIGN KEY (address_id) REFERENCES address (id);
        END IF;
    END $$;

DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints
                       WHERE constraint_name = 'fk_orders_on_user' AND table_name = 'orders') THEN
            ALTER TABLE orders ADD CONSTRAINT fk_orders_on_user FOREIGN KEY (user_id) REFERENCES users (id);
        END IF;
    END $$;

-- Modify columns only if they exist and have NOT NULL constraint
DO $$
    BEGIN
        IF EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'discount' AND column_name = 'end_date' AND is_nullable = 'NO') THEN
            ALTER TABLE discount ALTER COLUMN end_date DROP NOT NULL;
        END IF;
    END $$;

DO $$
    BEGIN
        IF EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'discount' AND column_name = 'start_date' AND is_nullable = 'NO') THEN
            ALTER TABLE discount ALTER COLUMN start_date DROP NOT NULL;
        END IF;
    END $$;