CREATE TABLE order_tracking
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    timestamp   TIMESTAMP WITHOUT TIME ZONE,
    description VARCHAR(255),
    location    VARCHAR(255),
    updated_by  VARCHAR(255),
    order_id    BIGINT                                  NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_order_tracking PRIMARY KEY (id)
);

-- Add foreign key constraint to orders table
ALTER TABLE order_tracking
    ADD CONSTRAINT FK_ORDER_TRACKING_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

-- Add indexes for better performance
CREATE INDEX idx_order_tracking_order_id ON order_tracking(order_id);
CREATE INDEX idx_order_tracking_status ON order_tracking(status);