CREATE TABLE payments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_id VARCHAR(255),
    tx_ref         VARCHAR(255),
    status         VARCHAR(255),
    amount         INTEGER                                 NOT NULL,
    currency       VARCHAR(255),
    email          VARCHAR(255),
    first_name     VARCHAR(255),
    last_name      VARCHAR(255),
    payment_time   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);


ALTER TABLE product_image_urls
DROP
CONSTRAINT fk_product_imageurls_on_product;

ALTER TABLE users
    ADD enabled BOOLEAN;

ALTER TABLE users
    ALTER COLUMN enabled SET NOT NULL;

DROP TABLE product_image_urls CASCADE;

DROP SEQUENCE reviews_seq CASCADE;