CREATE TABLE payments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_id VARCHAR(255),
    tx_ref         VARCHAR(255),
    status         VARCHAR(255),
    amount         INTEGER                                 NOT NULL,
    currency       VARCHAR(255),
    email          VARCHAR(255),
    first_name     VARCHAR(255),
    last_name      VARCHAR(255),
    payment_time   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);